### ISSUE TITLE
[BUG] Linux version as-cmd -b option does not take IP addresses after 0.2.1

### ISSUE THREAD

**Issue by nicholascw** [mkckr0/audio-share#100]
**Describe the bug**
as-cmd -b 0.0.0.0 still binds to the first IP address it finds on interfaces, only --bind=0.0.0.0 works.

**Server (please complete the following information):**
 - OS: Arch Linux  [e.g. Windows 10 22H2 19045.3570]
 - GUI or CMD: [e.g. GUI]
 - Version v0.2.1

**Android (please complete the following information):**
 - OS: OmniROM Android 14
 - Version v0.2.0

**Comment by mkckr0** [comment]
Duplicate with https://github.com/mkckr0/audio-share/issues/95#issuecomment-2465955838
