### ISSUE TITLE
[BUG] the capture format is not supported

### ISSUE THREAD

**Issue by mkckr0** [mkckr0/audio-share#102]
For me the gui app also broke since version 0.2.0. It seems like it can't capture the audio endpoint anymore. The android app is stuck for me at "starting" as well, but I don't know whether my issue is related to this one

`server.log` with version 0.1.0
```
[server] [info] server started
[server] [info] select audio endpoint: Lautsprecher (Sound Blaster Z)
[server] [info] WAVEFORMATEX: wFormatTag: 65534, nBlockAlign: 24
[server] [info] AudioFormat:
format_tag: 3
channels: 6
sample_rate: 48000
bits_per_sample: 32
```

and version 0.2.1
```
[server] [info] server started
[server] [info] select audio endpoint: Lautsprecher (Sound Blaster Z)
[server] [error] the capture format is not supported
```

_Originally posted by @CatDaniel in https://github.com/mkckr0/audio-share/issues/99#issuecomment-2481276706_

**Comment by mkckr0** [comment]
At present, more than 2 channels will cause this error.

**Comment by mkckr0** [comment]
@CatDaniel I build a fixed version. You can test it.
[AudioShareServer.zip](https://github.com/user-attachments/files/17811989/AudioShareServer.zip)

**Comment by CatDaniel** [comment]
Thanks, I tested the fixed build, and it works flawlessly. Really appreciate your incredibly fast response and effort in resolving this, it's really impressive!
