### ISSUE TITLE
[BUG] Server GUI crashes on launch and I have no idea why

### ISSUE THREAD

**Issue by KibSquib48** [mkckr0/audio-share#103]
**Describe the bug**
I double click AudioShareServer.exe and a window flashes for half a second, then immediately closes.

**Server (please complete the following information):**
 - OS: Windows 11 LTSC 24H2 (26100.2314)
 - GUI or CMD: GUI
 - Version 0.2.1

**Additional information**
vcredist 2015-2022 is installed and here is the log:
```
[2024-11-21 15:16:14.267] [server] [error] exit_on_failed  , 
[2024-11-21 15:21:20.640] [server] [error] exit_on_failed  , 
[2024-11-21 15:27:20.659] [server] [error] exit_on_failed  , 
```

**Comment by mkckr0** [comment]
Can the previous versions work normal?

**Comment by KibSquib48** [comment]
No, I tried 0.2.0 and 0.1.0 and both crashed in the same way.

**Comment by mkckr0** [comment]
Download the `audio-share-server-cmd-windows.zip`. Then use `as-cmd -l` to test.

**Comment by KibSquib48** [comment]
Output is `[2024-11-21 19:51:06.516] [error] exit_on_failed  ,`

**Comment by mkckr0** [comment]
The as-cmd has a bug #104. You can use the fixed one to test.
[as-cmd.zip](https://github.com/user-attachments/files/17854918/as-cmd.zip)

**Comment by KibSquib48** [comment]
Now it says `[2024-11-21 21:34:43.350] [error] exit_on_failed hr=-536870389, func=get_endpoint_list, message=GetValue, error=`
and I had to disable Windows Security to download it

**Comment by mkckr0** [comment]
The program can't read the `PKEY_Device_FriendlyName`. Open the Sound Panel, and take a screenshot of  playback device list.

**Comment by KibSquib48** [comment]
![image](https://github.com/user-attachments/assets/054c5190-5805-46cb-a83c-8140446a27ae)

**Comment by mkckr0** [comment]
Some devices don't have name. Use the fixed version to test.
[as-cmd.zip](https://github.com/user-attachments/files/17856435/as-cmd.zip)

**Comment by KibSquib48** [comment]
```
endpoint list:
          id: {0.0.0.00000000}.{209f9d61-39ea-4b0e-b236-6e26cb3ec63d} name: [Speakers]
        * id: {0.0.0.00000000}.{5ccbb29f-f681-482c-b317-563ae7971feb} name: Speakers (High Definition Audio Device)
          id: {0.0.0.00000000}.{755e3358-a0c7-41bb-8524-4de5f2c4efb7} name: Speakers (Echo Dot-2XV)
          id: {0.0.0.00000000}.{82a0eb1b-f390-4ec7-b9ec-416ab87a3499} name: Speakers (Steam Streaming Microphone)
          id: {0.0.0.00000000}.{e8f64557-847d-422c-b56f-db163bcdf140} name: Speakers (Steam Streaming Speakers)
total: 5
```
Seems like it works properly now

**Comment by mkckr0** [comment]
So the first "Virtual Speakers" doesn't have the `PKEY_Device_FriendlyName`.

**Comment by mkckr0** [comment]
Now the AudioShareServer.exe should work normal.
[AudioShareServer.zip](https://github.com/user-attachments/files/17856542/AudioShareServer.zip)

**Comment by KibSquib48** [comment]
> So the first "Virtual Speakers" doesn't have the `PKEY_Device_FriendlyName`. Where is it from? I want to install it to test.

I'm not sure, I think it's a leftover from some other phone speaker app that I installed but didn't work

**Comment by KibSquib48** [comment]
> Now the AudioShareServer.exe should work normal. [AudioShareServer.zip](https://github.com/user-attachments/files/17856542/AudioShareServer.zip)

Works perfectly now, thank you!
