### ISSUE TITLE
[BUG] Android App is crashing if "Dynamic Color from Color" is made empty

### ISSUE THREAD

**Issue by vizaie** [mkckr0/audio-share#107]
**Describe the bug**
Android App crashes if "Dynamic Color from Color" field is empty

In the Android App
1. Go to 'Settings'
2. "Dynamic Color from Color" field empty.
3. Application crashes

**Expected behavior**
It shouldn't crash the app. Either it should retain the previous value even after clicking ok or it shouldn't give the option to click ok when field is empty.

Server
 - OS: Arch linux 6.11.9-zen1-1-zen
 - GUI or CMD: Cmd
 - Version 0.2.1-2
 
Client
 - Device: Realme 9 pro +
 - OS: Android 14
 - Version

**Comment by mkckr0** [comment]
It will be fixed in v0.3.0

**Comment by mkckr0** [comment]
fixed at 792d0735f454b513972a6d6c337dcddb9a1a90ee
