### ISSUE TITLE
[BUG] Server crash when launching

### ISSUE THREAD

**Issue by shwwwa** [mkckr0/audio-share#116]
**Describe the bug**
GUI and cmd segmentation fault.
In cmd can't launch with the same error, however -l endpoint list works:
endpoint list:
        * id: {0.0.0.00000000}.{dee4afe5-99dc-4d19-996f-db0e5835fb1a} name: Line 1 (Virtual Audio Cable)
total: 1
Verbose doesnt print additional, server.log is empty.
vc_redist is installed.
Ipconfig info:
Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . : IGD_Rostelecom
   Link-local IPv6 Address . . . . . : fe80::8a81:b70a:5500:42d%18
   IPv4 Address. . . . . . . . . . . : 192.168.0.4
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.0.1

Really want to use this app because matebook d14 has glitchy audio
- shwwwa
**To Reproduce**
Launch ./as-cmd.exe -b or server app

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - OS: Win 10
 - GUI or CMD: GUI and CMD
 - Version 0.3.1

**Additional information**
Add any other information about the problem here, such as server.log or stdout.

**Comment by mkckr0** [comment]
run `as-cmd.exe -V -b` and see the output

**Comment by shwwwa** [comment]
as I said, verbose does not print anything additional

**Comment by mkckr0** [comment]
I build a debug version [as-cmd.zip](https://github.com/user-attachments/files/18266581/as-cmd.zip)
Download [ProcDump](https://learn.microsoft.com/en-us/sysinternals/downloads/procdump) then run `procdump.exe -e -x .\ as-cmd.exe -b` to collect dump file(as-cmd.exe_*.dmp) and post it.

**Comment by shwwwa** [comment]
[as-cmd.exe_241228_154025.dmp](https://github.com/user-attachments/files/18266649/as-cmd.exe_241228_154025.dmp)

**Comment by shwwwa** [comment]
wait sorry, ran non-debug version

**Comment by shwwwa** [comment]
[as-cmd.exe_241229_014200.dmp](https://github.com/user-attachments/files/18266651/as-cmd.exe_241229_014200.dmp)

**Comment by mkckr0** [comment]
It seems like your vc_redist version is 14.36.32532.0. Install the latest https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 and test again.

**Comment by mkckr0** [comment]
[as-cmd.zip](https://github.com/user-attachments/files/18268219/as-cmd.zip)
Use this release version to test because debug verion need to install VS2022

**Comment by shwwwa** [comment]
Thank you, looks like installing newer version of vc_redist helped me to get rid off segfault.
