### ISSUE TITLE
[BUG] Audio crackling sound

### ISSUE THREAD

**Issue by Ironfist69** [mkckr0/audio-share#18]
**Describe the bug**
Getting distorted, crackling sound when connecting Windows PC with Android.

**To Reproduce**
1. Download and install the latest build
2. Connect PC with Phone and there you go, enjoy the crackling sound

**Expected behavior**
Has to be crystal clear sound.

**Server (please complete the following information):**
 - OS: Windows 10 22H2
 - GUI or CMD: GUI
 - Version : 0.0.11

**Android (please complete the following information):**
 - Device: Samsung Galaxy A13
 - OS: OneUI 5.1 (Android 13)
 - Version: 0.0.11

**Additional information**
Downgrading to v0.0.9 resolves the issue. You must downgrade to v0.0.9 inorder to get crystal, clear sound.

**Comment by thiendt2k1** [comment]
can confirm, error persist on 0.0.13 Android 10, downgraded to 0.0.9 solved it for me too

**Comment by clicky6** [comment]
same here

**Comment by clicky6** [comment]
But in 0.0.9 also When I play the same video at the same volume first from windows to android and then through android only why is the audio directly from android more louder than the one from windows even though the volume is the same for both?

**Comment by mkckr0** [comment]
What kind of CPU are you using? The CPU of my computer is `AMD Ryzen 7 5800X`. In fact, I can't reproduce this bug in my computer. I can only guess the critical code snippet that may cause this bug.

**Comment by mkckr0** [comment]
Fix at #24.

**Comment by Ironfist69** [comment]
> Fix at #24.

Closing this issue
