### ISSUE TITLE
[BUG] Wrong example given

### ISSUE THREAD

**Issue by pythonian23** [mkckr0/audio-share#19]
**Describe the bug**
The example provided by `as-cmd -h` is:
```
Example:
  as-cmd -l 192.168.3.2:65530 -e 48
```
This does not run `as-cmd` properly.

**To Reproduce**
1. `as-cmd -h`

**Expected behavior**
```
Example:
  as-cmd -b 192.168.3.2:65530 -e 48
```
It should probably be `-b`, not `-l`.

**Server (please complete the following information):**
 - OS: [openSUSE TUmbeweed 20231117]
 - GUI or CMD: [CMD]
 - Version [0.0.12]

**Comment by mkckr0** [comment]
Fix at #22.
