### ISSUE TITLE
It's a torjan virus 

### ISSUE THREAD

**Issue by Naiml007** [mkckr0/audio-share#21]
Trojan

**Comment by mkckr0** [comment]
If you don't believe the binaries, you can compile by yourself.

**Comment by NormTurtle** [comment]
> .exe doesn't run on Windows 11.

it does work  im on window 11

**Comment by mkckr0** [comment]
You need to install The Visual C++ Redistributable for Visual Studio 2015-2022.

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by Naiml007** [comment]
> You need to install The Visual C++ Redistributable for Visual Studio 2015-2022.
> 
> https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

[2023-12-05 11:48:11.529] [server] [error] exit_on_failed   Element not found.

[2023-12-05 11:48:14.045] [server] [error] exit_on_failed   Element not found.

[2023-12-05 11:48:25.604] [server] [error] exit_on_failed   Element not found.

[2023-12-05 11:48:38.037] [server] [error] exit_on_failed   Element not found.

[2023-12-05 11:49:11.625] [server] [error] exit_on_failed   Element not found.

**Comment by Naiml007** [comment]
![image](https://github.com/mkckr0/audio-share/assets/90306726/a26feff3-7588-4479-b0e9-3e1efc064f3c)

**Comment by Naiml007** [comment]
bruh 
where is he ! @mkckr0

**Comment by mkckr0** [comment]
Take a screenshot of running  AudioShareServer.exe to see the arguments.

**Comment by mkckr0** [comment]
Run `as-cmd -l` to see available audio endpoints.

**Comment by kudlav** [comment]
same here, running `as-cmd -l` prints just [error] exit_on_failed Element not found.

**Comment by kudlav** [comment]
the problem is when there is no Audio Endpoint in the Windows. The app is not able to handle that.

**Comment by mkckr0** [comment]
OK, I'll fix the crash. The most of PC has at least one audio endpoint while motherboard has a available audio speaker interface although you don't plug a real speaker.

**Comment by kudlav** [comment]
Hi, my latest motherboard adds and removes outputs only after connecting speaker/headphones into those plugs. Probably the same case as the original reporter.

**Comment by mkckr0** [comment]
Changing state of using audio enpoint will exit the app. It's a not a bug.

You can change some settings of Audio Adapter to let it always be working. e.g. For Realtek Audio Adapter, you can open Realtek Audio Console and switch on the settings as picture shown below.

![realtek](https://github.com/mkckr0/audio-share/assets/26296627/9d9e4855-23e5-450c-9d71-e1e2dbab70c1)

**Comment by mkckr0** [comment]
Fix at #22 .
