### ISSUE TITLE
[BUG] Server GUI crash when ...

### ISSUE THREAD

**Issue by Nitrowing** [mkckr0/audio-share#26]
**Describe the bug**
Server immediately closes

**To Reproduce**
1. Run .exe
2. Click on Start Server
3. Box closes

**Expected behavior**
The server to run

**Server (please complete the following information):**
 - OS: [Windows 11]
 - GUI 
 - Version [e.g. v0.0.11]

**Android (please complete the following information):**
 - Device: [BlackShark 5]
 - OS: [Android 13]

**Comment by mkckr0** [comment]
Does server.log have any content?
