### ISSUE TITLE
[BUG] rattling sound when connecting windows to android

### ISSUE THREAD

**Issue by tejpalDarro** [mkckr0/audio-share#28]
**Describe the bug**
When I connect to 5.8GHz WiFi on my laptop, my Android is making a rattling sound.

**To Reproduce**
1. Go to 'your PC/laptop and connect wirelessly with your router using the 5.8Ghz band frequency. Then, start the server on your PC/laptop.
2. Click on 'The start icon on the app, you will hear a rattling sound.'

**Expected behavior**
A clear sound comes out of your Android phone, without any rattling sound.

**Server (please complete the following information):**
 - OS: [e.g. Windows 10 22H2 19045.3570]
 - GUI or CMD: [e.g. GUI]
 - Version [e.g. v0.0.14]

**Android (please complete the following information):**
 - Device: [Realme X2 Pro]
 - OS: [Android 11]
 - Version [e.g. v0.0.14]

**Additional information**
But when connecting to a 2.4GHz band, there is no rattling sound.

**Comment by mkckr0** [comment]
Take your phone connected with 5GHz and walk close to the WiFi router. If you can hear a clear sound, then it's a signal reason. 5GHz signal is not better than 2.4GHz when your device is far from router.

**Comment by tejpalDarro** [comment]
> Take your phone connected with 5GHz and walk close to the WiFi router. If you can hear a clear sound, then it's a signal reason. 5GHz signal is not better than 2.4GHz when your device is far from router.

I change my router, and now there is no rattling sound. Even on the 5Ghz band
