### ISSUE TITLE
[New Feature] Make the localhost 192.168***** ip default please.

### ISSUE THREAD

**Issue by almahmudbd** [mkckr0/audio-share#29]
**Describe the new feature you'd like**
Dear audioshare team,

I'm a user of the audioshare software and overall, I'm happy with it. However, I'd like to provide feedback on two aspects that could be improved:

1. Default IP selection:
I suggest changing the default selected IP to the local host's IP (19.168.***.***) . Most people connect to audioshare using their lan's local host IP, so this would be more convenient for users.

2. Auto-start with Windows:
Adding an "auto-start with Windows" feature would be helpful. This would automatically launch audioshare whenever Windows starts up, offering users a smoother experience.

Thank you for your time and consideration. 

**Additional context**
![Screenshot 2024-01-07 085915](https://github.com/mkckr0/audio-share/assets/13126441/0d3da86d-a55e-4097-a8e4-de7775a32016)
here is recommended scene

**Comment by mkckr0** [comment]
Done at #30.
