### ISSUE TITLE
[Question/Feature] Linux Support

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [mkckr0/audio-share#3]
Any chance of adding support, or more specifically, making a dedicated application for Linux?

**Comment by mkckr0** [comment]
It's a good idea to support Linux, but I have to learn audio programming of Linux. Maybe it will take a long time.

**Comment by chromer030** [comment]
Linux support would be great feature.
Also these days pipewire is dominating in Linux distros and it's easier than before for adding support.

**Comment by mkckr0** [comment]
I'm not sure about what kind of audio server should use, Pulse Audio or Pipewire. Which one is better?

**Comment by chromer030** [comment]
> Which one is better?

Pipewire is new and far better in design, performance, lower delay etc.
Pulse Audio is older and is used for compatibility.
Almost every project is adding support for pipewire, the latest i saw is qemu.

Pipewire also supports almost all other implementations by routing the request through a module to pipewire server.
The modules are:
- pipewire-alsa
- pipewire-ffado
- pipewire-jack
- pipewire-pulse
- pipewire-roc
- pipewire-v4l2
- pipewire-x11-bell

**Comment by mkckr0** [comment]
Ok. I'll try it.

**Comment by mkckr0** [comment]
The Linux cmd version has been released.
[v0.0.10](https://github.com/mkckr0/audio-share/releases/tag/v0.0.10)
