### ISSUE TITLE
[BUG] Less louder when playing through audio-share than on the actual device with same volume.

### ISSUE THREAD

**Issue by clicky6** [mkckr0/audio-share#34]
**Describe the bug**
When I play the same video at the same volume first from windows to android and then through android only, Why is the audio directly from android more louder than the one from windows even though the volume is the same for both?

**To Reproduce**
1. Connect audio-share android and windows using usb tethering as it gives more clear audio.
2. Play the same video file first from windows to android and then through android only keeping the volume of android same for both.
3. The one which is played from windows to android is less loud than the one directly from android.

**Expected behavior**
The loudness should have been the same between same media played from windows to android and that same media played directly on android as we are keeping the volume same.

**Screenshots**

**Server (please complete the following information):**
 - OS: Windows 11 23H2 22631.3007
 - GUI or CMD: GUI
 - Version v0.0.15

**Android (please complete the following information):**
 - Device: Samsung Galaxy Tab A8
 - OS: Android 13
 - Version v0.0.15

**Additional information**
Add any other information about the problem here, such as server.log or stdout.

**Comment by mkckr0** [comment]
To get the same loudness, you need to keep max volume of Windows and video player, then keep same volume of your phone.

**Comment by clicky6** [comment]
> To get the same loudness, you need to keep max volume of Windows and video player, then keep same volume of your phone.

I kept the volume 100 (max) on the new windows media player and the system volume was also on 100 (max but muted as then the speakers will also play).
Still there was a considerable difference in the volume.

**Comment by mkckr0** [comment]
See #36 and https://github.com/mkckr0/audio-share?tab=readme-ov-file#about-volume

**Comment by mkckr0** [comment]
Have you downloaded the v0.0.16?

**Comment by mkckr0** [comment]
I'll release the v0.0.17. Don't use v0.0.16.

**Comment by mkckr0** [comment]
> > See #36 and https://github.com/mkckr0/audio-share?tab=readme-ov-file#about-volume
> 
> OK The Android volume and the App's volume are 2 different things, that's why the sound loudness wasn't matching, are you making it such that the android volume is only followed and not the app volume?

No. The reason why they don't match is still unclear. But I add the "Loudness Enhancer", which can make sound louder to match system volume.

**Comment by mkckr0** [comment]
See #37.
