### ISSUE TITLE
[BUG] There is a null endpoint_id on my laptop.  It is actually 0.

### ISSUE THREAD

**Issue by JamesNorword2nd** [mkckr0/audio-share#35]
**Describe the bug**

./as-cmd -b 192.168.50.131
[2024-01-14 17:27:45.218] [info] pipewire header_version: 0.3.48, library_version: 0.3.48
endpoint_id is empty

**To Reproduce**
go to command line and type this in -- 

./as-cmd -l 192.168.50.131
[2024-01-14 17:28:50.888] [info] pipewire header_version: 0.3.48, library_version: 0.3.48
endpoint_list:
total: 0

**Expected behavior**
I love that is works on windows, but alas I want to use it on Linux.  Please help me out.
**Screenshots**

**Server (please complete the following information):**
 - OS: [Linuxt Mint 21.2 Victoria]
 - GUI or CMD: [CMD]
 - Version [e.g. v0.0.15]

**Android (please complete the following information):**
 - Device: [e.g. Pixel 4XL]
 - OS: [e.g. Android 13]
 - Version [e.g. v0.0.14]

**Additional information**
Add any other information about the problem here, such as server.log or stdout.

**Comment by mkckr0** [comment]
If your Linux doesn't have any output endpoint, your audio player can't run normally. Run `pw-play -v test.wav` to check it.

**Comment by JamesNorword2nd** [comment]
Very well.  Here is the result: 

pw-play -v CantinaBand3.wav
opened file "CantinaBand3.wav" format 00010002 channels:1 rate:22050
using default channel map: MONO
rate=22050 channels=1 fmt=s16 samplesize=2 stride=2 latency=2205 (0.100s)
connecting playback stream; target_id=4294967295
stream state changed unconnected -> connecting
stream param change: id=2
stream properties:
	media.type = "Audio"
	media.category = "Playback"
	media.role = "Music"
	application.name = "pw-play"
	media.filename = "CantinaBand3.wav"
	media.name = "CantinaBand3.wav"
	node.name = "pw-play"
	media.format = "WAV (Microsoft)"
	node.latency = "2205/22050"
	node.rate = "1/22050"
	stream.is-live = "true"
	node.autoconnect = "true"
	media.class = "Stream/Output/Audio"
now=0 rate=0/0 ticks=0 delay=0 queued=0
remote 0 is named "pipewire-0"
core done
core done
stream state changed connecting -> paused
stream state changed paused -> error
stream node 35 error: no node available
remote error: id=3 seq:7 res:-2 (No such file or directory): no node available

**Comment by mkckr0** [comment]
Does other Music player work normally?

**Comment by JamesNorword2nd** [comment]
I will probably have to do that.  Why wouldn't the laptop speakers themselves count? I must be missing something.  I'm doing more research today.

**Comment by mkckr0** [comment]
Maybe your speaker driver is not properly installed. Linux can't recognize some old laptop's hardware.

**Comment by mkckr0** [comment]
I'll close the issue. If you still have problem, you can reopen it.

**Comment by egayghost** [comment]
> Does other Music player work normally? If they not, then you may install a virtual speaker to let them work normally.

Any instruction to this? I'm on Mint 21.3, I remember AudioRelay let me did the same thing...

**Comment by mkckr0** [comment]
Same as #55.
