### ISSUE TITLE
[BUG] Failing to connect to server

### ISSUE THREAD

**Issue by EbnedI** [mkckr0/audio-share#38]
**Describe the bug**
Connection timed out when trying to connect to the server.  The Android app and computer executable have the same LAN adress and port but fail to connect. The phone is connected via WiFi and the computer via Ethernet

**To Reproduce**
1. Start Audio Share server in computer
2. Open Audio Share app and edit the host adress
3. See error "connection timed out"

**Screenshots**
![Audioshareapk](https://github.com/mkckr0/audio-share/assets/25856448/7dcfacfc-57f7-4d59-8c71-8b19713945e4)
![audioshare](https://github.com/mkckr0/audio-share/assets/25856448/ddd214c9-7d5c-409e-8f94-8ed77e6bbb7e)

**Server:**
 - OS: Windows 11 x64
 - GUI 
 - Version 0.0.17
**Android:**
 - Device: [Motorola g60]
 - OS: [Android 12]
 - Version 0.0.15 from F-Droid

**Comment by mkckr0** [comment]
It will show firewall dialog when you first time click "Start Server", keep default options and click "Allow Access".

Open "wf.msc" to check the firewall rules. The rule name may be "Audio Share Server" or "audioshareserver.exe" in "Inbound Rules".

**Comment by EbnedI** [comment]
You're right, it was the firewall. For some reason the firewall dialog didn't show up when starting the server but I went to the firewall settings and allowed Audio Share, then tried to connect with my phone and the problem was solved.
