### ISSUE TITLE
Mute PC

### ISSUE THREAD

**Issue by irose50** [mkckr0/audio-share#4]
Is there a way to just have audio on the phone and not on PC as well?

**Comment by mkckr0** [comment]
The monitor of PC may help you do this. Just mute the monitor's audio then choose the graphic card's audio as audio interface. On my PC, it is "Nvidia High Definition Audio".

**Comment by mkckr0** [comment]
I don't kown why you want to do this. If you have a speaker of PC, then you may needn't to start this app.

**Comment by irose50** [comment]
Hi. Reason I don't want sound on PC( actually it's a laptop) is because I want the sound to be in my hearing aids. So the audio from the laptop gets sent to the phone and the phone is already able to output to hearing aids. It works just fine except  I can still hear it on the laptop. The laptop is unable to send directly to hearing aids as Windows does not support the protocol used.

**Comment by irose50** [comment]
As I will mainly be using for YouTube, I've just discovered I can mute the main laptop volume and still control sound via YouTube itself. That solves my issue. Thanks

**Comment by mkckr0** [comment]
Yes, the laptop's monitor don't have volume buttons. I also find a way to do this. Just click system mute button, but remain the volume to a value you want.
![新建位图图像](https://github.com/mkckr0/audio-share/assets/26296627/99fe55a7-a639-4806-a391-ae1114d38c7e)
