### ISSUE TITLE
[New Feature] Requesting for in-app update feature (Auto update notifier)

### ISSUE THREAD

**Issue by Ironfist69** [mkckr0/audio-share#40]
**Describe the new feature you'd like**
I propose to add in-app update feature.

**Describe the reason why you want to add the feature**
I need this feature because users don't have to come to github and download and install the apk manually to update the app.

**Describe how to implement the feature if you can**
![Screenshot_20240121_130637_Seal](https://github.com/mkckr0/audio-share/assets/70436487/793fe039-1b17-42e5-bd79-9942b7064802)

Should look like this
_(Concept from JunkFood02/Seal (https://github.com/JunkFood02/Seal)_

**Additional context**
Windows and Android both should have in-app update feature

**Comment by mkckr0** [comment]
Accept

**Comment by mkckr0** [comment]
Done at #73.
