### ISSUE TITLE
[BUG] No sound on Arch Linux

### ISSUE THREAD

**Issue by airisama019** [mkckr0/audio-share#43]
**Describe the bug**
as-cmd starts and shows no errors, I can also connect with android device and it says "started" but there is no sound.
It works on Debian and Fedora. Fedora pipewire version is same as arch linux but still works. Was working on arch linux untill a few months ago. 

**To Reproduce**
1. Install arch linux with Installation Guide.
2. Install pipewire with "sudo pacman -S pipewire wireplumber pipewire-pulse pipewire-jack pipewire-alsa"
3. Enable pipewire service with "systemctl enable --user pipewire wireplumber pipewire-pulse"
4. Start as-cmd with "./as-cmd -b [your-ip]"

**Screenshots**
![Screenshot from 2024-02-15 21-16-15](https://github.com/mkckr0/audio-share/assets/155326638/846e8287-9aaf-4cc2-bc08-bbb96e0b7ae6)

![Screenshot from 2024-02-15 21-16-23](https://github.com/mkckr0/audio-share/assets/155326638/67c5e201-832e-40d1-b2b1-6e3abcf262d6)

![Screenshot_20240215-210139_Audio Share](https://github.com/mkckr0/audio-share/assets/155326638/ebcb3468-e7a1-4748-829b-e1edf42c2d69)

**Server (please complete the following information):**
 - OS: Arch Linux
 - GUI or CMD: CMD
 - Version: v0.0.17

**Android (please complete the following information):**
 - Device: Moto G5S
 - OS: Android 12L and 11 tested
 - Version: v0.0.17

**Additional information**
**Add any other information about the problem here, such as server.log or stdout.**
There is no such option on as-cmd usage help.

**more**
It's fine if you don't want to fix, I'll just reinstall debian or something.

**Comment by airisama019** [comment]
There is sound if I plug headphones so it's not a driver issue.

**Comment by mkckr0** [comment]
Run `pw-play -v test.wav` to check whether playback works normal.
https://github.com/mkckr0/audio-share/issues/31#issuecomment-1884729278

**Comment by airisama019** [comment]
here is output file
![output.txt](https://github.com/mkckr0/audio-share/files/14311028/output.txt)

seems to be working fine.

Also I thought issue would be their recent change from dbus to dbus-broker but I rolled back and still no sound on as-cmd.

**Comment by airisama019** [comment]
https://github.com/mkckr0/audio-share/assets/155326638/a85797c3-aafb-483e-bd01-e1b08ab6ec90

I used "ffmpeg -i out.wav out.mp4" so I can upload the file.
Sent to phone through smb share and it plays just fine.

**Comment by airisama019** [comment]
Nevermind I'm dumb
I forgot it uses both tcp and udp and I forgot to enable udp as well.
After enabling both it started working again.
Sorry for wasting your time.

**Comment by airisama019** [comment]
Maybe say "Error: can't connect to udp or tcp port" on android app to make it easier.
