### ISSUE TITLE
[BUG]  No longer working after Arch update (PC). (console command) Version: v0.0.17

### ISSUE THREAD

**Issue by niereklamuj** [mkckr0/audio-share#49]
No longer working after Arch update on my PC.

**To Reproduce**
Update Arch Linux with "pacman -Syyu".

**Expected behavior**
Please update or recompile to the newest Arch Linux packages for compatibility with pipewire.

The error looks like:

as-cmd -b 192.168.42.226
[2024-03-03 19:33:25.743] [info] pipewire header_version: 0.3.48, library_version: 1.0.3
bind: Cannot assign requested address

**Comment by mkckr0** [comment]
The IP address is changed. Run `ip addr` to see available address.

**Comment by niereklamuj** [comment]
Yes, my apology, I broke my IP address. Thank you!
