### ISSUE TITLE
[New Feature] Add a tile in Quick Settings

### ISSUE THREAD

**Issue by dzmtrzz** [mkckr0/audio-share#50]
**Describe the new feature you'd like**
I propose to add a button to the notification panel that would toggle the playback on and off,

**Describe the reason why you want to add the feature**
I need this feature because it's convenient and you don't need to unlock the screen to start it when it times out.
[this thing](https://developer.android.com/about/versions/nougat/android-7.0.html#tile_api)

**Describe how to implement the feature if you can**
https://developer.android.com/reference/android/service/quicksettings/Tile

**Additional context**

**Comment by mkckr0** [comment]
Good idea.

**Comment by mkckr0** [comment]
finished at 84574d837a402b6c6dfbd6e5dae68187eb31d521
