### ISSUE TITLE
[Suggestion] Simplifying the server setup

### ISSUE THREAD

**Issue by hideki2k02** [mkckr0/audio-share#52]
**Describe the new feature you'd like**
I propose to add some kind of feature that would make it simpler/faster to set-up the Audio Server for less experienced people.

**Describe the reason why you want to add the feature**
Currently I'm having to run the program at startup as my Audio Card is dead, and having to run `./as-cmd -l` every time because the Endpoint keeps changing is a little inconvenient. It is currently possible to automate it with scripts but not all users might be able to do that.

**Describe how to implement the feature if you can**
Make the program automatically pick the first endpoint that is found (Works for most people unless they have multiple audio devices)

I'm currently using this bash script to get the program running at startup:
```bash
IPV4=$(hostname -I | awk '{print $1}')
ENDPOINT=$(./as-cmd -l | grep id | grep -Eo '[0-9]{1,4}')

if [ "$1" ]; then
    IPV4=$1
fi

if [ "$2" ]; then
    ENDPOINT=$2
fi

./as-cmd -e $ENDPOINT -b $IPV4
```

**Comment by marurunk** [comment]
I wrote my script too, I rename the bin to audio-share to use killall
and use notify-send (for linux mint) if doesn't work and say that
![imagen](https://github.com/mkckr0/audio-share/assets/100788648/80d9c131-63c1-4b3d-ae52-b9d6d7c467cd)

**Comment by hideki2k02** [comment]
Nice! Will definitely make a few changes to my script after that haha

I've noticed the Windows version has a GUI, maybe something like `./as-cmd -gui` would also be nice for some people.

**Comment by mkckr0** [comment]
For audio endpoint, It has already had a default value. If you don't set `-b`, it will use the default endpoint.

For ip address, I'll add a default value for `-b`. It will be the first LAN IPv4 address as #29.

**Comment by mkckr0** [comment]
Finished #88
