### ISSUE TITLE
[BUG] Can't connect to server

### ISSUE THREAD

**Issue by saiyaswanth007** [mkckr0/audio-share#53]
**Server :**
 - OS: [Windows 11 Version 23H2 for x64-based Systems (KB5035853)]
 - GUI or CMD: [e.g. GUI]
 - Version [e.g. v0.0.11]

**Android (please complete the following information):**
 - Device: [Xioami 11T pro]
 - OS: [Android 13]

**error**
i have started server on the windows 11 and the server is started but in android it is not connecting and both are in the same wifi
![image](https://github.com/mkckr0/audio-share/assets/112363854/2439592e-5079-4be0-91a6-4c4acbeebde8)
![WhatsApp Image 2024-03-14 at 21 53 48_3beb4cd3](https://github.com/mkckr0/audio-share/assets/112363854/0bb4248e-47e6-49bb-b183-5f4cc7e27eea)

**Comment by mkckr0** [comment]
Open `wf.msc` to check whether firewall rules are normal in inbound list.

**Comment by mkckr0** [comment]
#38

**Comment by saiyaswanth007** [comment]
Yeah they are normal
![image](https://github.com/mkckr0/audio-share/assets/112363854/40228926-c6d1-4698-a705-06f22df6e8ba)

**Comment by mkckr0** [comment]
Check the configuration of firewall. Make sure the firewall won't block all inbound connection.
![1](https://github.com/mkckr0/audio-share/assets/26296627/e9b47339-dbef-4d79-8859-053521c69098)

**Comment by saiyaswanth007** [comment]
![IMG_20240316_115859.jpg](https://github.com/mkckr0/audio-share/assets/112363854/f5167207-2ff3-43ed-8ca6-24aefcaa11a4)
They are normal.....i think it is due my college wifi when i connected my friend's hotspot it is working👍
