### ISSUE TITLE
[BUG] Endpoint 0

### ISSUE THREAD

**Issue by egayghost** [mkckr0/audio-share#55]
I'm on LInux Mint 21.3 and as I check for endpoint, I ended up with 0 and can't able to use the program. I remember AudioRelay has some instruction to create virtual speaker in order to work which you can check it [HERE](https://docs.audiorelay.net/instructions/linux/stream-audio-from-your-linux-pc-to-your-phone) but I'm not sure if it applies the same for audioshare. A help is very much appreciated, thank you.

**Comment by mkckr0** [comment]
The AudioReplay use PulseAudio. Audio Share use Pipewire. It may not work normally.

Linux Mint 21 seems like using pulse audio as default audio server. Can music player work normally before you installing Pipewire? Or your PC has an embedded sound card? If not, then you need a virtual device.

Copy the below config to `~/.config/pipewire/pipewire.conf.d/audio-share-sink.conf` to create a virtual sink node.
```
context.objects = [
    {   factory = adapter
        args = {
           factory.name     = support.null-audio-sink
           node.name        = "Audio Share Sink"
           media.class      = Audio/Sink
           object.linger    = true
           audio.position   = [ FL FR ]
           priority.session = 1009
           priority.driver  = 1009
           monitor.channel-volumes = true
           monitor.passthrough = true
        }
    }
]
```
Run `systemctl --user restart pipewire` to restart the pipewire.
Then run `as-cmd -l`, you will see the new endpoint.
```
[abc@localhost ~]$ ./audio-share-server-cmd/bin/as-cmd -l
[2024-03-17 22:46:14.563] [info] pipewire header_version: 0.3.48, library_version: 0.3.67
endpoint_list:
        * id: 30   name: Audio Share Sink
total: 1
```
Then the `as-cmd -b` will work normally.

**Comment by egayghost** [comment]
> The AudioReplay use PulseAudio. Audio Share use Pipewire. It may not work normally.
> 
> Linux Mint 21 seems like using pulse audio as default audio server. Can music player work normally before you installing Pipewire? Or your PC has an embedded sound card? If not, then you need a virtual device.
> 
> Copy the below config to `~/.config/pipewire/pipewire.conf.d/audio-share-sink.conf` to create a virtual sink node.
> 
> ```
> context.objects = [
>     {   factory = adapter
>         args = {
>            factory.name     = support.null-audio-sink
>            node.name        = "Audio Share Sink"
>            media.class      = Audio/Sink
>            object.linger    = true
>            audio.position   = [ FL FR ]
>            priority.session = 1009
>            priority.driver  = 1009
>            monitor.channel-volumes = true
>            monitor.passthrough = true
>         }
>     }
> ]
> ```
> 
> Run `systemctl --user restart pipewire` to restart the pipewire. Then run `as-cmd -l`, you will see the new endpoint.
> 
> ```
> [abc@localhost ~]$ ./audio-share-server-cmd/bin/as-cmd -l
> [2024-03-17 22:46:14.563] [info] pipewire header_version: 0.3.48, library_version: 0.3.67
> endpoint_list:
>         * id: 30   name: Audio Share Sink
> total: 1
> ```
> 
> Then the `as-cmd -b` will work normally.

I actually have an embedded sound card, and seems like I have pipewire installed as well, do I need to do something here like removing pulseaudio or something? sorry kinda noob..

**Comment by mkckr0** [comment]
Run `pactl` to check the pipewire.
![1](https://github.com/mkckr0/audio-share/assets/26296627/aab3748c-5bdd-4763-9e25-b0d5f4d94369)

**Comment by egayghost** [comment]
> Run `pactl info` to check the pipewire. ![1](https://private-user-images.githubusercontent.com/26296627/313483714-aab3748c-5bdd-4763-9e25-b0d5f4d94369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2ODg3NDgsIm5iZiI6MTcxMDY4ODQ0OCwicGF0aCI6Ii8yNjI5NjYyNy8zMTM0ODM3MTQtYWFiMzc0OGMtNWJkZC00NzYzLTllMjUtYjBkNWY0ZDk0MzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE1MTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZDE1NTZlOGUxNDkzODYwNWVmNmE1MjEyOGE3ZmFjNDEzNTZiZGQxY2FlNmUxOGM2YzdmMzAxNWY5ZmVjODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cOp9qHGbpvytSkQfHjR9aYK_q201gMJuyH4lmwbOdVU)

![image](https://github.com/mkckr0/audio-share/assets/59923073/c4abf3fe-2c3d-4e4c-9e4f-e845cdd2f4ff)
seems like it's using pulseaudio :/

**Comment by mkckr0** [comment]
Follow the instrunction of `https://linuxgenie.net/install-pipewire-on-linux-mint-21/`.

**Comment by egayghost** [comment]
> Follow the instruction of https://linuxgenie.net/install-pipewire-on-linux-mint-21/.

I did manage to create a virtual speaker and enable pipewire, however, I cannot play any audio lol.

**Comment by mkckr0** [comment]
You must configure pipewire properly. Did you disable the pulse audio?

**Comment by mkckr0** [comment]
Follow  the instructions, you can't remove pulse audio directly. Because other system  components may require it.

**Comment by egayghost** [comment]
> Follow the instructions, you can't remove pulse audio directly. Because other system components may require it.

Yeah, I just did, it's working now, thanks...

![image](https://github.com/mkckr0/audio-share/assets/59923073/274b3eb0-fe54-4f62-a9a6-a3bd8183c1a6)
