### ISSUE TITLE
Auto Start

### ISSUE THREAD

**Issue by cucu02** [mkckr0/audio-share#7]
This is a very amazing application. Hopefully the developer will add auto start to the Android version so that it runs automatically when the smartphone is restarted.

**Comment by mkckr0** [comment]
Please tell me more details about why you want it auto start after system reboot. Auto start this app and auto play? But you still need to start the server manually. It's not reasonable.

**Comment by cucu02** [comment]
Automatically starting the application will be very helpful if the smartphone is used as a wireless speaker placed on several floors of a building. I see there is great potential for this, especially in educational institutions in Indonesia. For fixed servers, this is done manually with a fixed IP.

**Comment by mkckr0** [comment]
Ok. I'll try it.

**Comment by outusuke** [comment]
I don't know if it should be added as a new issue but add the auto reconnect function when connection is lost or reset

**Comment by mkckr0** [comment]
> I don't know if it should be added as a new issue, but add auto reconnect function to the app when connection is lost or reset and a auto start when the audio share server is initiated

For connection being lost or reset, you can turn on "Ignore Battery Optimizations" settings.

**Comment by outusuke** [comment]
> > I don't know if it should be added as a new issue, but add auto reconnect function to the app when connection is lost or reset and a auto start when the audio share server is initiated
> 
> For connection being lost or reset, you can turn on "Ignore Battery Optimizations" settings.

It has already been done, but if the audio server stops for some reason the app does not start automatically

**Comment by eMPee584** [comment]
it showed **Connection close by peer** a bunch of times for me yesterday.. should reconnect in these cases i reckon..

**Comment by mkckr0** [comment]
finished at 84574d837a402b6c6dfbd6e5dae68187eb31d521
