### ISSUE TITLE
[BUG] i have a very specific bug report

### ISSUE THREAD

**Issue by ansarimohammed422** [mkckr0/audio-share#71]
**Describe the bug**
the bug is when i connect my phone through audio-share to my linux pc it streams audio to my phone
but when i play any youtube on any browser on my pc like (firefox,chromium,gnome web) the youtube is not playing any videos
but when i mute the video from youtube it is played

and VLC is not also streaming audio it only plays videos

but with "STREMIO" a video streaming app the video is playing with audio with no issues what should i do

**To Reproduce**
1. connect phone
2. play any other audio file from pc it is streamed
3. open youtube on any video streaming website on any browser the video is not played
4. but when i mute that video from that website it is played

**Expected behavior**
I expect the video to be played with audio

**Screenshots**

**Server (please complete the following information):**
 - OS: [e.g. Arch Linux]
 - GUI or CMD: [e.g. CMD]
 - Version [e.g. v0.0.17]

**Android (please complete the following information):**
 - Device: [e.g. poco x4 pro 5g]
 - OS: [e.g. Android 13]
 - Version [e.g. v0.0.17]

**Additional information**
Add any other information about the problem here, such as server.log or stdout.

**Comment by mkckr0** [comment]
I'm not clear about what you said:
> but when i mute the video from youtube it is played

It means that you hear the delayed sound?
You can use https://www.youtube.com/watch?v=ucZl6vQ_8Uo to test the delay.

**Comment by ansarimohammed422** [comment]
I mean when i play any local video on my pc the audio is streamed
But when i try to watch any video through any browser the audio is not streamed and video is not played but when i mute the audio from browser the video is played

**Comment by mkckr0** [comment]
> I mean when i play any local video on my pc the audio is streamed But when i try to watch any video through any browser the audio is not streamed and video is not played but when i mute the audio from browser the video is played

Can your video on browser play normally when `as-cmd` isn't running?

**Comment by ansarimohammed422** [comment]
Yes and also it is played normally when i mute the video from youtube or other site

**Comment by mkckr0** [comment]
So the problem is not caused by `as-cmd`. It may be something wrong about PipeWire.

**Comment by ansarimohammed422** [comment]
I think so no because without usibg as-cmd
Although audio is not streamed the video is played normally
Without muting it on youtube or any other platform
