### ISSUE TITLE
VirusTotal detect virus in exe

### ISSUE THREAD

**Issue by soyangelromero** [mkckr0/audio-share#8]
![image](https://github.com/mkckr0/audio-share/assets/128564349/06a19fc8-2c1e-4589-b1d0-b421c1723a9b)

https://www.virustotal.com/gui/file/4f355ed76035a37c967433bbbb3132b1f9e12e4036e70f2778a1abf99470c835

**Comment by mkckr0** [comment]
All the releases of this repo were built by Github Action. The hash of file can be found in Github Action's log, which is same as it.
https://github.com/mkckr0/audio-share/actions/runs/6325040201/job/17175753233

I press Reanalyze, and then no security vendor report it, but still has a sandbox report it.
![image](https://github.com/mkckr0/audio-share/assets/26296627/4a3c64e1-cb17-4d25-bda2-6fd7bf670dbc)

**Comment by Naiml007** [comment]
![Screenshot_2023-12-04-19-57-35-725_com android chrome](https://github.com/mkckr0/audio-share/assets/90306726/7d034e68-0e18-4a6a-b557-f69773ce09d7)
