### ISSUE TITLE
[BUG] Android client not connecting

### ISSUE THREAD

**Issue by martypower2064** [mkckr0/audio-share#83]
**Describe the bug**
after  "as-cmd -b 192.168.122.1" has been ran in the host pc the android client throws: "No route to host: /192.168.122.1:65530"

**To Reproduce**
go through all the installation steps

**Expected behavior**
the android device should connect to the host

**Screenshots**
![image](https://github.com/user-attachments/assets/9b96a304-4ee4-4db2-8db8-f0eef3d34475)

![Screenshot_20241003-222520_Audio Share](https://github.com/user-attachments/assets/5fe10f89-cc80-4654-9e84-67e4eab94d37)

**Server (please complete the following information):**
 - OS: arch linux
 - GUI or CMD: fish shell running on Konsole terminal
 - Version v0.1.0

**Android (please complete the following information):**
 - Device: samsung A20e
 - OS: Android 11
 - Version v0.1.0

**Additional information**
i have no firewall turned on, the default ip (192.168.3.2) was not working for hosting and threw [this](https://github.com/user-attachments/assets/d153fef8-7c8a-4c8e-82fa-b741137820ce) error

**Comment by mkckr0** [comment]
The phone must connect same network with PC. Check the IP of your phone.

**Comment by martypower2064** [comment]
i am 100% that i am on the same network on both devices, also what would i do with my phone's ip ?

**Comment by mkckr0** [comment]
![Screenshot_1728002645](https://github.com/user-attachments/assets/d37560c7-5436-4d66-b193-024cb444e831)
Make sure it is `192.168.122.xxx`

**Comment by martypower2064** [comment]
both my host ip and phone ip are similar

**Comment by mkckr0** [comment]
You should bind `10.95.15.xxx` not `192.168.122.1`.

**Comment by martypower2064** [comment]
wait how was i suposed to know that

**Comment by martypower2064** [comment]
![image](https://github.com/user-attachments/assets/02065f61-f00c-437a-bb21-f8422622d1c6)

**Comment by mkckr0** [comment]
Use `ip addr` to see available IP addresses of PC.

**Comment by martypower2064** [comment]
ok it apears its working perfectly now, im sorry for the inconvenience
