### ISSUE TITLE
[BUG] Server starts a new instance after hibernation

### ISSUE THREAD

**Issue by kudlav** [mkckr0/audio-share#84]
**Describe the bug**

Audio Share Server creates a new instance which leads to port collision every time the Windows is resumed from Hibernation mode

**To Reproduce**
1. Install Audio Share Server on Windows
2. Enable _Auto run the app when system starts_
3. Set _When app starts_ to _Start server_
4. Start the server
5. Hibernate the computer
6. Wake up the computer
7. Another instance is created and the error occurs.

**Expected behavior**
New instances should not be created.

**Screenshots**
![image](https://github.com/user-attachments/assets/5f1f2a82-1d4d-47af-a545-10cf3a89e09a)
![image](https://github.com/user-attachments/assets/64f0fdca-0687-49ee-a8e5-00e828dc4541)

**Server:**
 - OS: Windows 11 23H2 (22631.4317)
 - GUI
 - Version 0.1.0

**Android:**
 - Not connected

**Comment by mkckr0** [comment]
I can't reproduce the bug on Windows 10. Even so, I can add an option to enable single instance check.
