### ISSUE TITLE
[New Feature] ? possible to share audio between android tv to android phone ?

### ISSUE THREAD

**Issue by RahifM** [mkckr0/audio-share#86]
**Describe the new feature you'd like**
I propose to add ... android audio share between android tv to android phone

**Describe the reason why you want to add the feature**
I need this feature because ... itll help me watch movies on my tv with audio wirelessly coming through the android phone headphones

**Describe how to implement the feature if you can**
Use the interface https://docs.example.com ... im not sure how to add it but please looks into it, thanks :))

**Additional context**

**Comment by mkckr0** [comment]
Duplicate with #9
