### ISSUE TITLE
[BUG] Server segmentation fault when starting on linux

### ISSUE THREAD

**Issue by Kurty00** [mkckr0/audio-share#93]
**Describe the bug**
The as-cmd gives me a segmentation fault when I run as-cmd 

**To Reproduce**
1. Extract the release, copy bin/as-cmd to ~/.local/bin/
2. run as-cmd
3. zsh: segmentation fault (core dumped)  as-cmd -h

**Expected behavior**
I expect the binary not to crash.

**Server (please complete the following information):**
 - OS: Manjaro KDE
 - GUI or CMD: CMD
 - Version 0.2.0
 - zsh

**Comment by outusuke** [comment]
I have the same problem, but I notice that it occurs when the VPN is enabled

**Comment by mkckr0** [comment]
Can you provide the full output log and core dump file?

**Comment by mkckr0** [comment]
I guess it may be caused by `ifa_addr` didn't check null.
https://github.com/mkckr0/audio-share/blob/1bf2e5e83f9538fdd6561c7b52004536ae8760f1/server-core/src/network_manager.cpp#L88

I compile a fixed version, you can test it.
[as-cmd.zip](https://github.com/user-attachments/files/17608928/as-cmd.zip)

**Comment by outusuke** [comment]
> I guess it may be caused by `ifa_addr` didn't check null.
> 
> https://github.com/mkckr0/audio-share/blob/1bf2e5e83f9538fdd6561c7b52004536ae8760f1/server-core/src/network_manager.cpp#L88
> 
> I compile a fixed version, you can test it. [as-cmd.zip](https://github.com/user-attachments/files/17608928/as-cmd.zip)

It’s working now.

**Comment by Kurty00** [comment]
Works for me too. Thank you.

**Comment by mkckr0** [comment]
#97
