### ISSUE TITLE
[BUG] as-cmd only binds to the default port.

### ISSUE THREAD

**Issue by visagemsc** [mkckr0/audio-share#95]
**Describe the bug**
`as-cmd` only binds to the default port.

**To Reproduce**
1. Run `as-cmd -b x.x.x.x:12000` (or any other port)
2. `[info] tcp listen success on x.x.x.x:65530`
3. `[info] udp listen success on x.x.x.x:65530`

**Expected behavior:**
1. `[info] tcp listen success on x.x.x.x:12000`
2. `[info] udp listen success on x.x.x.x:12000`
3. Should be able to connect on port 12000.

**Server (please complete the following information):**
 - OS: Debian 12
 - GUI or CMD: CMD
 - Version: 0.2.0

**Comment by mkckr0** [comment]
It's a bug of cxxopts. You should use `as-cmd --bind=x.x.x.x:12000`. Other formats such as `as-cmd -b x.x.x.x:12000` or `as-cmd --bind x.x.x.x:12000` will all use the default value as if `x.x.x.x:12000` is not specified.

I'll fix it in future by using a new cmdline parser.

**Comment by visagemsc** [comment]
That's good to know. I desperately needed this version to work since 0.1.0 had problems sending the audio (probably when I updated pipewire) while this one didn't and I managed to hardcode the desired port and rebuilt it but it's good to know I actually didn't need to do that.
