### ISSUE TITLE
[New Feature] Remove DependencyInfoBlock for F-Droid

### ISSUE THREAD

**Issue by linsui** [mkckr0/audio-share#98]
**Describe the new feature you'd like**
We find that there is a `DependencyInfoBlock` in your APK.

It's a [Signing block](https://bi-zone.medium.com/easter-egg-in-apk-files-what-is-frosting-f356aa9f4d1) added by AGP and encrypted with the Google public key so it can't be read by anyone else except Google. You can read more about it [here](https://gitlab.com/fdroid/admin/-/issues/367) and [here](https://gitlab.com/fdroid/fdroidserver/-/issues/1056).

While this was added a while ago, we were only enforcing it for new apps, and recently we started scanning updates too.

Could you please disable it with the following code?

```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

Thanks!

**Describe the reason why you want to add the feature**
I need this feature because ...

**Describe how to implement the feature if you can**
Use the interface https://docs.example.com ...

**Additional context**

**Comment by mkckr0** [comment]
Done!

**Comment by linsui** [comment]
Thanks!
