### ISSUE TITLE
[BUG] Android app stuck "starting" after updating to latest

### ISSUE THREAD

**Issue by Terramoto** [mkckr0/audio-share#99]
**Describe the bug**
Upgraded to 0.2.1 from 0.1.0 on both Windows and Android, server on Windows starts fine but when i try to connect on Android the states changes to "Starting" indefinitely.

**To Reproduce**
1. Start 0.2.1 service on Windows
2. Connect from the Android apk
3. Press connect

**Expected behavior**
Expected sound or successful connection

**Server (please complete the following information):**
 - OS: Windows 11
 - GUI
 - 0.2.1

**Android (please complete the following information):**
 - Device: Xiaomi 11t pro
 - OS: Android 14
 - Version 0.2.1

**Additional information**
Data was cleared on android, service whitelisted on windows firewall.
Reverting to previous version on both devices restores it's function.
initially tried 0.1.0 apk on 0.2.1 service, connection was successful but all i got was static noise.

**Comment by mkckr0** [comment]
- Check the version of "AudioShareServer.exe" and "Audio Share" app, and keep them all being `0.2.1`.
- Click the "Repair Firewall" button in "AudioShareServer.exe" to fix the firewall rules.

If it still donesn't work, then see the `server.log`, which is located at the same folder with "AudioShareServer.exe".

**Comment by CatDaniel** [comment]
For me the gui app also broke since version 0.2.0. It seems like it can't capture the audio endpoint anymore

`server.log` with version 0.1.0
```
[server] [info] server started
[server] [info] select audio endpoint: Lautsprecher (Sound Blaster Z)
[server] [info] WAVEFORMATEX: wFormatTag: 65534, nBlockAlign: 24
[server] [info] AudioFormat:
format_tag: 3
channels: 6
sample_rate: 48000
bits_per_sample: 32
```

and version 0.2.1
```
[server] [info] server started
[server] [info] select audio endpoint: Lautsprecher (Sound Blaster Z)
[server] [error] the capture format is not supported
```

**Comment by mkckr0** [comment]
@Terramoto You may have same problem with #102

**Comment by Terramoto** [comment]
> @Terramoto You may have same problem with #102

Ive been away for a while but i do remember seeing the messaged logged about the format not being supported. Ill try the fixed version tomorrow and report back.

**Comment by Terramoto** [comment]
Tested the version on #102 was not able to run it.
![image](https://github.com/user-attachments/assets/5a272080-c75c-44da-ae62-40a98f6d3a03)
this and several other errors came up, i did install the vc package in the requirements and i don't get this issue with older versions. Could i be missing something else?

**Comment by mkckr0** [comment]
It's a debug version, which need debug dll. You can use this release version.
[AudioShareServer.zip](https://github.com/user-attachments/files/17830907/AudioShareServer.zip)
